# Generated by Django 5.1.6 on 2025-03-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_productgallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='url',
            field=models.CharField(max_length=300),
        ),
    ]
