# Generated by Django 5.1.6 on 2025-03-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_productgallery_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transactiondetail',
            name='user',
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='backend.transaction'),
        ),
    ]
