# Generated by Django 5.1.6 on 2025-03-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_transaction_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.CharField(default='', max_length=30),
        ),
    ]
