# Generated by Django 5.1.6 on 2025-03-29 06:11

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_productgallery_url_productgallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(default='bg-masthead.jpg', upload_to=backend.models.product_gallery_upload_path),
        ),
    ]
